Update how empty array is initialized
This is to fix the following error in the CI build:

  error: array_init: no type specified (maybe: `[]Type{}` instead of `[]`)

This probably started happening with Vlang 0.4.9, which has changes
to empty arrays (see https://github.com/vlang/v/issues/22828 and
https://github.com/vlang/v/blob/master/CHANGELOG.md).