Fix compile error in circular buffer
Fixes the following compiler error due to a recent change in V:

  Error: temp/circular_buffer.v:20:20: error: cannot prepend `T` to `[]T`
     18 |         return error('Buffer is full')
     19 |     }
     20 |     b.content.prepend(value)
        |                       ~~~~~
     21 | }
     22 |
  Error: temp/circular_buffer.v:36:20: error: cannot prepend `T` to `[]T`
     34 |     }
     35 |
     36 |     b.content.prepend(value)
        |                       ~~~~~
     37 | }
     38 |
  checker summary: 2 V errors, 0 V warnings, 0 V notices

Resolves #277.