Update to work with Vlang 0.4.9 (#237)
* Update how empty array is initialized

This is to fix the following error in the CI build:

  error: array_init: no type specified (maybe: `[]Type{}` instead of `[]`)

This probably started happening with Vlang 0.4.9, which has changes
to empty arrays (see https://github.com/vlang/v/issues/22828 and
https://github.com/vlang/v/blob/master/CHANGELOG.md).

* Update utf8.get_uchar to .get_rune

This is to fix the following warning:

  warning: function `encoding.utf8.get_uchar` has been deprecated since 2024-11-17, it will be an error after 2025-05-16; use `.get_rune(s string, index int)` instead

[no important files changed]